version: "3"
services:

 mongo:
  image: asderel/p1gps:db
  deploy:
   replicas: 1 # para escabilidad del servicio.
   resources:
    limits:
     cpus: "0.15"
     memory: 200M
   restart_policy:
    condition: on-failure #reinicar el contenedor si falla
  ports:
   - "28017:28017" 
   - "27017:27017"
  volumes:
   - "db-data:/data/db" # para dar persistencia a la sesión
 order:
  image: asderel/p1gps:order
  depends_on:
   - "mongo" #le psamos al servicio order la ip del servicio mongo
  deploy:
   replicas: 1
   resources:
    limits:
     cpus: "0.2"
     memory: 300M #subid los límites si podéis/le cuesta arrancar
   restart_policy:
    condition: on-failure
  ports:
   - "8080:8080"
 web:
  image: asderel/p1gps:web
  deploy:
   replicas: 1
   resources:
    limits:
     cpus: "0.25"
     memory: 300M
   restart_policy:
    condition: on-failure
  ports:
   - "80:8080"

volumes:
 db-data:
